name: Build and deploy mkdocs on gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        repository: cheshire-cat-ai/core
        ref: main
        # Relative path under $GITHUB_WORKSPACE to place the repository
        path: core
#        sparse-checkout: |
#          cat

    - name: Change Directory
      run : |
        cp -r /home/runner/work/docs/core/cat /home/runner/work/docs/docs
        ls -a 
        cd /home/runner/work/docs/docs
        ls -a 

    - name: Build site 🏗️
      run: |
        ls -a 
        mkdocs build

    - name: Deploy to GitHub Pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        force_orphan: true